name: "Nix Build"

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    name: Build Nix Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v14
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build package
        run: |
          nix-build shell.nix --no-out-link
